enum AuthActionTypes {
  LOGOUT = 'LOGOUT',
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  SET_LOADING = 'SET_LOADING',
  END_LOADING = 'END_LOADING',
  SET_ERROR = 'SET_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
}

export default AuthActionTypes;
